[package]
name = "c05-yew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# this is the development version of Yew
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
